docs_dir: doc/book/ru
pages:
    - index.md
site_name: workflow-log
site_description: 'Компонент, являющиейся фабрикой для создания логеров в прилоежние.'
repo_url: 'https://github.com/old-town/old-town-log'
copyright: 'Copyright (c) 2016 <a href="https://github.com/old-town/">OldTown</a>'